--
-- PostgreSQL database dump
--

-- Dumped from database version 14.17 (Homebrew)
-- Dumped by pg_dump version 17.0

-- Started on 2025-05-15 19:37:54 -03

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: caio
--

-- *not* creating schema, since initdb creates it


ALTER SCHEMA public OWNER TO caio;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 210 (class 1259 OID 16908)
-- Name: denuncia; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.denuncia (
    den_id bigint NOT NULL,
    den_data date,
    den_texto character varying(255),
    den_titulo character varying(255),
    den_urgencia integer,
    tip_id bigint NOT NULL,
    usu_id integer NOT NULL
);


ALTER TABLE public.denuncia OWNER TO postgres;

--
-- TOC entry 209 (class 1259 OID 16907)
-- Name: denuncia_den_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.denuncia ALTER COLUMN den_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.denuncia_den_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 212 (class 1259 OID 16916)
-- Name: feedback; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.feedback (
    fee_id bigint NOT NULL,
    fee_texto character varying(255),
    den_id bigint
);


ALTER TABLE public.feedback OWNER TO postgres;

--
-- TOC entry 211 (class 1259 OID 16915)
-- Name: feedback_fee_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.feedback ALTER COLUMN fee_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.feedback_fee_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 214 (class 1259 OID 16922)
-- Name: orgaos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.orgaos (
    org_id integer NOT NULL,
    org_nome character varying(255)
);


ALTER TABLE public.orgaos OWNER TO postgres;

--
-- TOC entry 213 (class 1259 OID 16921)
-- Name: orgaos_org_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.orgaos ALTER COLUMN org_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orgaos_org_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 216 (class 1259 OID 16928)
-- Name: tipo; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tipo (
    tip_id bigint NOT NULL,
    tip_nome character varying(255)
);


ALTER TABLE public.tipo OWNER TO postgres;

--
-- TOC entry 215 (class 1259 OID 16927)
-- Name: tipo_tip_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tipo ALTER COLUMN tip_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tipo_tip_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 16934)
-- Name: usuario; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuario (
    usu_id integer NOT NULL,
    usu_cpf character varying(255),
    usu_email character varying(255),
    usu_nivel integer,
    usu_nome character varying(255),
    usu_senha character varying(255)
);


ALTER TABLE public.usuario OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 16933)
-- Name: usuario_usu_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.usuario ALTER COLUMN usu_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuario_usu_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3703 (class 0 OID 16908)
-- Dependencies: 210
-- Data for Name: denuncia; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.denuncia VALUES (1, '2023-05-12', 'Semaforo da Av. da Saudade está quebrado', 'Semaforo quebrado', 4, 1, 2);


--
-- TOC entry 3705 (class 0 OID 16916)
-- Dependencies: 212
-- Data for Name: feedback; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3707 (class 0 OID 16922)
-- Dependencies: 214
-- Data for Name: orgaos; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.orgaos VALUES (1, 'SEDUC');
INSERT INTO public.orgaos VALUES (2, 'PM');
INSERT INTO public.orgaos VALUES (3, 'PC');
INSERT INTO public.orgaos VALUES (4, 'SETRAN');


--
-- TOC entry 3709 (class 0 OID 16928)
-- Dependencies: 216
-- Data for Name: tipo; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.tipo VALUES (1, 'TRANSITO');
INSERT INTO public.tipo VALUES (2, 'EDUCACAO');
INSERT INTO public.tipo VALUES (3, 'AMBIENTAL');


--
-- TOC entry 3711 (class 0 OID 16934)
-- Dependencies: 218
-- Data for Name: usuario; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.usuario VALUES (1, '53108444816', 'martarocha@gmail.com', 1, 'Marta Rocha', '$2a$10$hGK1PBqaq/Q6fGR2Diwi0e9lzp/N6HIrI9zcEb19bSJoQC/S.0r5a');
INSERT INTO public.usuario VALUES (2, '939492222', 'viniboquete@gmail.com', 2, 'Vinicius Boqueteiro', '$2a$10$fQ98RGR./Cm4u7jgP00u2.Jne4pyckhh2lnPBQ1gXoDruWEJBiwli');


--
-- TOC entry 3718 (class 0 OID 0)
-- Dependencies: 209
-- Name: denuncia_den_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.denuncia_den_id_seq', 1, false);


--
-- TOC entry 3719 (class 0 OID 0)
-- Dependencies: 211
-- Name: feedback_fee_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.feedback_fee_id_seq', 1, false);


--
-- TOC entry 3720 (class 0 OID 0)
-- Dependencies: 213
-- Name: orgaos_org_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.orgaos_org_id_seq', 1, false);


--
-- TOC entry 3721 (class 0 OID 0)
-- Dependencies: 215
-- Name: tipo_tip_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tipo_tip_id_seq', 1, false);


--
-- TOC entry 3722 (class 0 OID 0)
-- Dependencies: 217
-- Name: usuario_usu_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.usuario_usu_id_seq', 2, true);


--
-- TOC entry 3549 (class 2606 OID 16914)
-- Name: denuncia denuncia_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.denuncia
    ADD CONSTRAINT denuncia_pkey PRIMARY KEY (den_id);


--
-- TOC entry 3551 (class 2606 OID 16920)
-- Name: feedback feedback_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.feedback
    ADD CONSTRAINT feedback_pkey PRIMARY KEY (fee_id);


--
-- TOC entry 3555 (class 2606 OID 16926)
-- Name: orgaos orgaos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orgaos
    ADD CONSTRAINT orgaos_pkey PRIMARY KEY (org_id);


--
-- TOC entry 3557 (class 2606 OID 16932)
-- Name: tipo tipo_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tipo
    ADD CONSTRAINT tipo_pkey PRIMARY KEY (tip_id);


--
-- TOC entry 3553 (class 2606 OID 16942)
-- Name: feedback ukdkl07tpatddy1xm5isahl0quo; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.feedback
    ADD CONSTRAINT ukdkl07tpatddy1xm5isahl0quo UNIQUE (den_id);


--
-- TOC entry 3559 (class 2606 OID 16940)
-- Name: usuario usuario_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT usuario_pkey PRIMARY KEY (usu_id);


--
-- TOC entry 3562 (class 2606 OID 16953)
-- Name: feedback fknhgiuc1748991aoqph9iihp0t; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.feedback
    ADD CONSTRAINT fknhgiuc1748991aoqph9iihp0t FOREIGN KEY (den_id) REFERENCES public.denuncia(den_id);


--
-- TOC entry 3560 (class 2606 OID 16948)
-- Name: denuncia fkrq4i3al1ubnug3bigbb51nsci; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.denuncia
    ADD CONSTRAINT fkrq4i3al1ubnug3bigbb51nsci FOREIGN KEY (usu_id) REFERENCES public.usuario(usu_id);


--
-- TOC entry 3561 (class 2606 OID 16943)
-- Name: denuncia fktcpfakuclyg8x9v6qbis6yjbg; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.denuncia
    ADD CONSTRAINT fktcpfakuclyg8x9v6qbis6yjbg FOREIGN KEY (tip_id) REFERENCES public.tipo(tip_id);


--
-- TOC entry 3717 (class 0 OID 0)
-- Dependencies: 4
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: caio
--

REVOKE USAGE ON SCHEMA public FROM PUBLIC;
GRANT ALL ON SCHEMA public TO PUBLIC;


-- Completed on 2025-05-15 19:37:54 -03

--
-- PostgreSQL database dump complete
--

